HTTP Method: GET
URL: http://localhost:8000/listings/:id

HTTP Method: POST
URL: http://localhost:8000/listings

HTTP Method: PUT
URL: http://localhost:8000/listings/:id

HTTP Method: DELETE
URL: http://localhost:8000/listings/:id