//GET all users:

Get: http://localhost:8000/listingsHTTP/1.1 //Returns a JSON array of user objects.

//GET a single user by ID:

GET : http://localhost:8000/listings/HTTP/1.1

//POST (Create) a new user:

URL: http://localhost:8000/listings //HTTP Method: POST

//PUT (Update) a user by ID:

URL: http://localhost:8000/:id //HTTP Method: PUT

//DELETE a user by ID: URL: http://localhost:8000/:id //HTTP Method: DELETE